
# What do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  on this name we reference in container
  name: mongo-pvc
spec:
#  this key:value MUST math with PersistentVolume
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#      This value should be less than or equal to the capacity of the PV it is bound to.

---

# How do we want it implemented(configuration of real physical storage on cloud)
#while the capacity parameter in the PV YAML file defines the total storage capacity
#  of the volume, the resources.requests.storage parameter in the PVC YAML file specifies
#  the amount of storage that the PVC wants to claim from the PV.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 5Gi
#
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/some-new/directory/structure/"
    type: DirectoryOrCreate

# Binding its a process when we bind a PersistentVolumeClaim and PersistentVolume.
# Its mine a PersistentVolumeClaim fine PersistentVolume by: storageClassName, accessModes and capacity????
