
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616

# kubectl port-forward svc/fleetman-queue 30010:8161


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30011
# kubectl port-forward svc/fleetman-webapp 30011:80
