
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616

# kubectl port-forward svc/queue 30010:8161


#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: position-tracker
#spec:
##  type: NodePort
#  selector:
#    app: queue
#
#  ports:
#    - name: http
#      port: 8080
##      nodePort: 30010