apiVersion: v1
kind: Service
#  Service defines which pods are going to be represented by this service
#  Service is a virtual network endpoint for either other services
#  or maybe external request form browser for example
metadata:
  name: service1
spec:
#  type: ClusterIP
# Services with type ClusterIP(have stable private IP for using in K8s Cluster only). Like a privete IP

  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

# kubectl port-forward service/queue 30080:80

---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  selector:
    app: queue
    release: "1"
  ports:
    - name: queue
      port: 8161
      nodePort: 30081
