apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: ns1
  labels:
    app: test
spec:
  containers:
    - name: test
      image: mysql/mysql-server:8.0.23
      env:
        - name : MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: fleetman
---

apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: ns1
spec:
  selector:
    app: test
  ports:
    - port: 3306
  type: ClusterIP


