apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fleetman
  region: us-east-2

nodeGroups:
  - name: ng-fleetman
    instanceType: t2.large
    desiredCapacity: 3
    maxSize: 4
    minSize: 3
    volumeSize: 10
    volumeType: gp2