apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
# template for the pods
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
#          local env image: richardchesterwood/k8s-fleetman-queue:release2-arm64
          image: richardchesterwood/k8s-fleetman-queue:release2


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
  labels:
    app: position-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: position-simulator
  # template for the pods
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
        - name: position-simulator
#          local env image: richardchesterwood/k8s-fleetman-position-simulator:release2-arm64
          image: richardchesterwood/k8s-fleetman-position-simulator:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
  labels:
    app: position-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: position-tracker
  # template for the pods
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker
#          local image: richardchesterwood/k8s-fleetman-position-tracker:release3-arm64
          image: richardchesterwood/k8s-fleetman-position-tracker:release3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  # template for the pods
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
#          local env image: richardchesterwood/k8s-fleetman-api-gateway:release2-arm64
          image: richardchesterwood/k8s-fleetman-api-gateway:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  # template for the pods
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
#          local env image: richardchesterwood/k8s-fleetman-webapp-angular:release2-arm64
          image: richardchesterwood/k8s-fleetman-webapp-angular:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice



